require:
  - rubocop-rails

AllCops:
  Include:
    - 'Rakefile'
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
